### ISSUE TITLE
TypeError: Object ... has no method 'includes

### ISSUE THREAD

**Issue by MatthieuStigler** [jiho/chroma#3]
Hi

You might already know it, but just in case: I tried the dev version, and now face some errors...

Thanks!!

``` r
devtools::install_github("jiho/chroma")
#> Skipping install of 'chroma' from a github remote, the SHA1 (c24168e5) has not changed since last install.
#>   Use `force = TRUE` to force installation
library("chroma")
#> 
#> Attaching package: 'chroma'
#> The following objects are masked from 'package:grDevices':
#> 
#>     hcl, hsv, rgb
show_col(interp_colors(6, colors=c("#002855", "#DAAA00")))
#> Error in context_eval(join(src), private$context): TypeError: Object 3,4,6,7,8,9 has no method 'includes'
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jiho** [comment]
Works for me with the current version c24168e5

**Comment by MatthieuStigler** [comment]
True, I tried from another computer and had no issue. Some internal package conflict I guess. Will close for now.

**Comment by m-sterr** [comment]
Hi,

I have the exact same issue. Do you have any idea how to fix this?

Thanks a lot!
